# Generated by Django 4.2.24 on 2025-09-24 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.CharField(choices=[('general', 'General'), ('diseño web', 'Diseño Web'), ('programación', 'Programación')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='articulo',
            name='contenido',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='articulo',
            name='duracion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articulo',
            name='fecha_registro',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='image',
            field=models.ImageField(blank=True, upload_to='articulos'),
        ),
    ]
