# Generated by Django 4.2.24 on 2025-09-29 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_articulo_categoria_articulo_contenido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(default='')),
                ('autor', models.CharField(max_length=255)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.articulo')),
            ],
        ),
    ]
