# Generated by Django 4.2.24 on 2025-09-29 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.CharField(default='anónimo', max_length=255),
        ),
    ]
